kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "dawarich.fullname" . }}-config
  labels:
    {{- include "dawarich.labels" . | nindent 4 }}
data:
  {{- include "dawarich.environmentSetup" (dict "environment" .Values.env)}}
